const { getMailerConfig, createTransporter } = require("./_mailer");

function setCors(res) {
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "OPTIONS,POST");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
}

function toSafeText(value) {
  return String(value || "").trim();
}

module.exports = async function handler(req, res) {
  setCors(res);

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ success: false, error: "Method not allowed" });
  }

  const { type, applicants = [], thresholdDays, reason } = req.body || {};
  const alertType = toSafeText(type).toLowerCase();
  if (!alertType) {
    return res.status(400).json({ success: false, error: "Missing alert type." });
  }

  const mailerConfig = getMailerConfig();
  if (!mailerConfig.pass) {
    return res.status(500).json({
      success: false,
      error: "Missing MAILER_PASSWORD environment variable.",
    });
  }

  try {
    const transporter = createTransporter(mailerConfig);
    const list = Array.isArray(applicants) ? applicants : [];

    let subject = "ALOHA Admin Alert";
    let html = "";

    if (alertType === "long_wait") {
      subject = `Long-Waiting Applicants Alert (${list.length})`;
      html = `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #D2042D;">Long Waiting Applicants</h2>
          <p><strong>Threshold:</strong> ${Number(thresholdDays) || 7} days</p>
          <p><strong>Total flagged:</strong> ${list.length}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 16px 0;">
          ${list
            .map(
              (item) => `
                <div style="margin-bottom: 12px;">
                  <strong>${toSafeText(item.name) || "Unknown Applicant"}</strong><br>
                  <span style="color:#64748b;">ID: ${toSafeText(item.id) || "N/A"} | Email: ${
                toSafeText(item.email) || "N/A"
              }</span><br>
                  <span style="color:#64748b;">Position: ${toSafeText(item.position) || "N/A"} | Waiting: ${
                Number(item.daysWaiting) || 0
              } day(s)</span>
                </div>
              `
            )
            .join("")}
          <p style="font-size: 12px; color: #888; margin-top: 20px;">Generated by ALOHA Admin Dashboard.</p>
        </div>
      `;
    } else if (alertType === "blacklist_attempt") {
      subject = "Blacklist Alert: Naughty Application Attempt";
      html = `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #D2042D;">Blacklist Triggered</h2>
          <p><strong>Reason:</strong> ${toSafeText(reason) || "Duplicate/invalid application attempt"}</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 16px 0;">
          ${list
            .map(
              (item) => `
                <div style="margin-bottom: 12px;">
                  <strong>${toSafeText(item.name) || "Unknown Applicant"}</strong><br>
                  <span style="color:#64748b;">Email: ${toSafeText(item.email) || "N/A"} | DOB: ${
                toSafeText(item.dob) || "N/A"
              }</span><br>
                  <span style="color:#64748b;">City: ${toSafeText(item.city) || "N/A"} | ID(s): ${
                toSafeText(item.id) || "N/A"
              }</span>
                </div>
              `
            )
            .join("")}
          <p style="font-size: 12px; color: #888; margin-top: 20px;">Generated by ALOHA Application Portal.</p>
        </div>
      `;
    } else {
      return res.status(400).json({ success: false, error: "Unsupported alert type." });
    }

    await transporter.sendMail({
      from: `"ALOHA Security Alerts" <${mailerConfig.user}>`,
      to: mailerConfig.notifyTo,
      subject,
      html,
    });

    return res.status(200).json({ success: true });
  } catch (error) {
    return res.status(500).json({
      success: false,
      error: error.message || "Failed to send admin alert email.",
    });
  }
};
